name: Build

on:
  push:
    branches:
    - master
    - edge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install build-essential

    - name: Prepare prebuilt cross-compile toolchain
      run: |
        mkdir ~/toolchain
        wget -c https://github.com/usertam/tc-build/releases/latest/download/tc-build-install.tar.xz -O - | tar -C ~/toolchain -xJ

    - name: Prepare build ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Prepare build environment
      run: |
        echo "$HOME/toolchain/bin" >> $GITHUB_PATH
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV
        echo '' > .scmversion

    - name: Compile the kernel
      run: make -j$(nproc) CC="ccache clang" O=out vendor/gta4lwifi_eur_open_defconfig all

    - name: Upload built kernel image
      uses: actions/upload-artifact@v2
      if: success()
      with:
        path: out/arch/arm64/boot/Image.gz
